### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by LovepreetSinghMe** [lf2com/magnet.js#12]
Hey I was surfing for a feature like yours on the internet and found this somehow but I am not able to include it inside my angular project. Can you publish this lib on npm

**Comment by lf2com** [comment]
Hi @LovepreetSinghMe, I published magnet.js on npm. Please try `npm i @lf2com/magnet.js` or `npm i https://github.com/lf2com/magnet.js`.

**Comment by LovepreetSinghMe** [comment]
Great work! @lf2com
