### ISSUE TITLE
ReferenceError: Cannot access 't' before initialization

### ISSUE THREAD

**Issue by cedricdelpoux** [lf2com/magnet.js#15]
Hello, I try to use magnet.js but I have this error `ReferenceError: Cannot access 't' before initialization`.

I checkout the code and I found:
```
const { top: t = (isset(t) ?t :y)} = rect;
```
`isset(t)` make this error because it has never been initialized

My import is :
```
import Magnet from "@lf2com/magnet.js/libs/magnet"
```

**Comment by lf2com** [comment]
OMG I didn't realize this critical issue! I will fix this issue as soon as possible. Also I will add eslint into magnet.js on the next milestone. Thank you for reminding!

**Comment by lf2com** [comment]
Hi @cedricdelpoux I fixed reference errors [here](https://github.com/lf2com/magnet.js/commit/133781118fa508e685b734ea8382978675ce36f8#diff-ff30a2efc7ce5f5ed85ad49f4594c121). Also updated that on npm. Please kindly help to check if this issue still happen.

**Comment by cedricdelpoux** [comment]
Thank you @lf2com . There are no errors anymore.
