### ISSUE TITLE
Remove console output

### ISSUE THREAD

**Issue by Moskito89** [lf2com/magnet.js#19]
`magnet.js` has `console.log(rect);` in line `532` which is a little bit disgusting. 
Is there a reason for logging every position? If not I'd like to remove that line and create a pull request then.

(If this functionality is important for debugging, I could imagine an separate function for that.)

**Comment by lf2com** [comment]
Sorry it was for debugging and I forgot to remove it. I just committed and released a [patch](https://github.com/lf2com/magnet.js/releases/tag/v1.0.8) for that.

**Comment by Moskito89** [comment]
Thank you so much for your fast reply! I'm looking forward to see this version in npm. :-)

**Comment by lf2com** [comment]
Thank you for reminding that issue! I just published the new version to npm. Please check it if you need :D
