### ISSUE TITLE
removing items from magnet group

### ISSUE THREAD

**Issue by rverderber** [lf2com/magnet.js#2]
Love this plugin! Been looking for something like this for a while. 

I'm having an issue removing elements for a magnet group. I want to disable an item after it is double clicked on so I can edit the containers content and would like the mouse events to be used to select text, not move the container. 

Should clearing the magnet object or removing all the items from the group stop the drag events from happening? or I am I misunderstanding the methods purpose?

**Comment by lf2com** [comment]
Hi @rverderber I made some changes to fix this issue: [Details](https://github.com/lf2com/magnet.js/commit/97fba941d342942f3dc68955f2cc1ab4e1c3a736). Please help to check if it works and can meet your need.
Now the remove/add function could work well. You can also try it on the [group demo](https://lf2com.github.io/magnet.js/demo/demo_groups.html). The blocks on the demo page could be removed from group if you double click or uncheck its checkbox, and add it back to that group when double click again or check its checkbox.

Here is the sample code about how to add/remove DOMs of group:
```javascript
let magnet = new Magnet();
let dom = document.getElementById('a-dom');
magnet.add(dom); // add to group
magnet.remove(dom); // remove from group
```

**Comment by rverderber** [comment]
That totally fixed it. Great Job!

I’ve been looking for a control that would act as an HTML5 Editor. Not like an editor for developing pages. More like one to edit Web2Print pieces (postcards, flyers, etc). If you check out Canva.com you can see what I’ve been looking for. I can’t find anything that exists just like it.

This simple plugin actually provides a very good base for creating such an editor. The other comment posted the same day I posted mine would be another step in that direction. Adding handles to the container on a hover event would allow you to resize the element while still having the various snapping effect white resizing as well as moving.

Would expanding this control to something more like a canva.com editor be something you would be interested in?

~rv


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by lf2com** [comment]
Thank you @rverderber. I wouldn't know this bug until you opened this issue.
Glad to hear that you apply this plugin to a so great idea project! If your team has already created a GitHub repository please let me know.

**Comment by rverderber** [comment]
This would probably be for a commercial venture. Would this be something you might be willing to working on for payment?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by rverderber** [comment]
Have you thought about integrating this with jquery UI? To use their drag controls. This is a little more advanced javascript than I’m use to working with and was wondering if you thought that might be do-able?

Thanks

Robert

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by lf2com** [comment]
Hi @rverderber 
Sorry, I missed the mail of github notification. It is a great idea for applying magnet.js into jquery UI. I'll add it to the milestone.
