### ISSUE TITLE
Import does not work

### ISSUE THREAD

**Issue by rockwellll** [lf2com/magnet.js#33]
Hi. So, i've installed the package with yarn

```
yarn add @lf2com/magnet.js
```

When i want to import `Magnet` with the following 

```
import Magnet from '@lf2com/magnet.js';
```

I get the following error

```
"export 'default' (imported as 'Magnet') was not found in '@lf2com/magnet.js'
```

Any idea why this happening? Thanks.

**Comment by lf2com** [comment]
Hi @rockwellll, sorry for replying late. I finally found out the key problem was that I didn't change `module.exports` to `export default` in `index.js`.
I've updated the change to v1.0.9. If you have time please give it a try. Thanks!

**Comment by rockwellll** [comment]
hi @lf2com, no worries. 

Thank you for your reply. Yes not it works perfectly!.
