### ISSUE TITLE
Aligning Center of Parent

### ISSUE THREAD

**Issue by graywolf336** [lf2com/magnet.js#6]
Is it possible to have magnetic points on the center of the parent container for both vertical and horizontal axis?

**Comment by lf2com** [comment]
Sorry for late reply. This is an useful idea. I'll add this function soon.

**Comment by graywolf336** [comment]
Awesome! I've been meaning to look into this library again and will definitely use it when this gets added :)

**Comment by lf2com** [comment]
Hi @graywolf336, I made some [changes](https://github.com/lf2com/magnet.js/releases/tag/v1.0.2) to support to align the center of parent element. Please give it a try and let me know if there is any need to improve.
Please notice that if you want the magnet members to align to their parent element, the `position` style of parent need to be changed to one of `relative`/`absolute`/`fixed` (excluding `static`) for the members to reference the base of position offset.

**Comment by graywolf336** [comment]
Awesome! :D 

I will give it a try either this week or next week. Thanks for working and implementing this!!

**Comment by lf2com** [comment]
Since this feature is implemented, I'd close this issue.
