### ISSUE TITLE
Request for adding magnet-free dragging without holding the ctrl key for some elements.

### ISSUE THREAD

**Issue by adityakrshnn** [lf2com/magnet.js#9]
Hi,
I must say you have a great plugin here! The only thing I wished to be present was the feature of attraction-less movement without holding the ctrl key for some elements. Like could you add another class called magnet-free or something that would allow that element to move with snap free movement all the time. Please do consider this at your own regard.

**Comment by lf2com** [comment]
Hi @adityakrshnn,
This is a great suggestion! I'll add this into the milestone. Thanks!

**Comment by lf2com** [comment]
Hi @adityakrshnn, I added `.allowCtrlKey(false)` for this feature to enable/disable the `ctrl` key's effect of magnet. Also, I added `.attractable(false)` to disable attract behavior which has the same effect as pressing `ctrl` key.
Currently magnet.js not support to set attractable independently for members. For moving without attract behavior on dragging some elements, it is recommended to call `.attractable(false)` when the `mousedown`/`touchstart` event of specific element. And call `.attractable(true)` when the `mouseup`/`touchend` event of that element.
Please try the [new version](https://github.com/lf2com/magnet.js/releases/tag/v1.0.2).

**Comment by adityakrshnn** [comment]
Thanks for building it so quickly. Great job!
